#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="${1:-$(pwd)}"
DEST="${2:-$HOME/.openclaw/workspace/skills}"
mkdir -p "$DEST"
cp -R "$REPO_DIR/skills/frontend-performance" "$DEST/"
cp -R "$REPO_DIR/skills/frontend-performance-audit" "$DEST/"
cp -R "$REPO_DIR/skills/react-performance" "$DEST/"
cp -R "$REPO_DIR/skills/webperf-core-web-vitals" "$DEST/"
cp -R "$REPO_DIR/skills/web-perf" "$DEST/"
cp -R "$REPO_DIR/skills/webperf-loading" "$DEST/"
cp -R "$REPO_DIR/skills/webperf-interaction" "$DEST/"
cp -R "$REPO_DIR/skills/webperf-media" "$DEST/"
cp -R "$REPO_DIR/skills/web-auto-analyzer" "$DEST/"
cp -R "$REPO_DIR/skills/performance-profiler" "$DEST/"
echo "Installed pack successfully to $DEST"
